// app/corpora/bills/index.js
// Bills = Indian Parliament's bill corpus.
// ~9,900 bills across 1952-2026 from sansad.in's getBills API,
// daily-mirrored via parliamentwatch-data's build_bills_sansad.py.
//
// Third registered corpus under SansadSaar (after DRSC and CAG).
// Pipeline-validation milestone: this module was the first added without
// fresh shell architecture — just slot it in. If something cracked here
// the v1.0a corpus-module shell would need a rethink before adding
// Hansard or Questions.
//
// Independence Principle: this file does not import from drsc/index.js
// or cag/index.js. Schema-shape helpers, parseQuery, etc., are duplicated
// from the CAG module by design. Refactor when a fourth corpus arrives
// and the duplication starts to bite.
//
// Sharded fetch: Bills uses index-meta.json + index-<NN>.json shards
// (~1 MB each), differing from DRSC's flat reports.json + CAG's
// reports.json. App fetches index-meta.json first, then all shards in
// parallel. Pre-emptive sharding decided 2026-05-10 — full archive is
// 10.5 MB single-file today (well under CF's 25 MiB cap), but PRS
// payload merge will grow it and changing on-disk shape after the app
// depends on it costs more than starting sharded.

import {
  idbGet, idbPut,
  escapeHtml, debounce,
  loadSettings, saveSettings,
} from '../../deps.js';

const CORPUS_PREFIX = 'bills/';

// ── Constants ───────────────────────────────────────────────────────────────

// House → pill-class suffix (reuses DRSC-styled house-pill CSS).
const HOUSE_INFO = {
  'Lok Sabha':   { short: 'LS', pill: 'L' },
  'Rajya Sabha': { short: 'RS', pill: 'R' },
};

// Status → cat-badge class (reuses CSS used by DRSC categories).
const STATUS_INFO = {
  'Pending':   { class: 'AT',     label: 'Pending'   },
  'Passed':    { class: 'DFG',    label: 'Passed'    },
  'Assented':  { class: 'ASSURE', label: 'Assented'  },
  'Lapsed':    { class: 'SUBJ',   label: 'Lapsed'    },
  'Withdrawn': { class: 'AT',     label: 'Withdrawn' },
  'Removed':   { class: 'AT',     label: 'Removed'   },
  'Negatived': { class: 'AT',     label: 'Negatived' },
};
const DEFAULT_STATUS = { class: 'AT', label: '—' };

const TYPE_INFO = {
  'Government':     { short: 'GOV', class: 'DFG'  },
  'Private Member': { short: 'PRV', class: 'SUBJ' },
};
const DEFAULT_TYPE = { short: '?', class: 'AT' };

const SUMMARY_PROMPT = `You are summarising a bill introduced in the Indian Parliament. Read the bill text below and produce a clear, plain-English briefing for a busy reader. Use this structure:

1. **What the bill does** (1-2 sentences — the substantive change in law)
2. **Key clauses / provisions** (3-6 bullets)
3. **Who is affected** (1-2 bullets)
4. **Status / fate** (where it stands in the legislative process — passed, lapsed, became an Act, etc., if discernible from the text)
5. **Why it matters** (1-2 sentences)

Keep it neutral, factual, and accessible to a non-specialist. Do not invent claims that aren't in the text.

BILL:
{TEXT}`;

function buildAskPrompt({ summary, text, searchResults, question }) {
  const parts = [
    'You are answering questions about a specific bill from the Indian Parliament. Use only the supplied material below to answer. If the answer isn\'t in the supplied material, say so clearly.',
  ];
  if (summary) parts.push('', 'SUMMARY (previously generated by AI):', summary);
  parts.push('', 'BILL:', text);
  if (searchResults && searchResults.length) {
    parts.push('', 'RECENT WEB CONTEXT (use cautiously, prefer the bill itself when they conflict):');
    for (const r of searchResults) parts.push(`- ${r.title}\n  ${r.url}\n  ${r.snippet}`);
  }
  parts.push('', '---', '', 'QUESTION: ' + question);
  return parts.join('\n');
}

// ── Module-private state ────────────────────────────────────────────────────

const state = {
  // records is a flat array (bills naturally don't group by committee).
  // indexMeta is the shard manifest. manifest is the human-readable stats
  // file (also includes per-bill `texts` map used to know which bills have
  // extracted text without per-bill probing).
  data: { records: [], indexMeta: null, manifest: null, meta: null },
  filtered: [],
  selectedBill: null,
  filters: { search: '', status: '', billType: '', billCategory: '', billYear: '', billIntroducedInHouse: '', sort: 'year_desc' },

  cache: {
    summaries: {},   // billKey -> string
    text:      {},   // billKey -> string (in-memory; IDB-backed)
    chats:     {},   // billKey -> [{role, content, error?}]
  },

  dialogChat: [],
  streamingContext: null,
};

let _deps = null;
let _activated = false;

// ── Helpers ─────────────────────────────────────────────────────────────────

function billKey(b) {
  return `bills|${b.compositeId}`;
}

function parseDate(s) {
  if (!s) return null;
  // sansad.in dates: "1990-08-17 00:00:00.0", "2026-03-13 00:00:00.0".
  const d = new Date(String(s).replace(' ', 'T'));
  if (!isNaN(d)) return d;
  // Fallback: midnight Jan 1 of billYear.
  return null;
}

function billDate(b) {
  return parseDate(b.billIntroducedDate)
      || parseDate(b.billPassedInLSDate)
      || parseDate(b.billPassedInRSDate)
      || (b.billYear ? new Date(`Jan 1, ${b.billYear}`) : null);
}

function statusInfo(b) {
  return STATUS_INFO[b.status] || DEFAULT_STATUS;
}

function typeInfo(b) {
  return TYPE_INFO[b.billType] || DEFAULT_TYPE;
}

function houseInfo(b) {
  return HOUSE_INFO[b.billIntroducedInHouse] || { short: '?', pill: 'L' };
}

function hasExtractedText(b) {
  // manifest.texts is keyed by compositeId; absence ⇒ no text yet.
  return !!state.data.manifest?.texts?.[b.compositeId];
}

function hasSummary(b) {
  return !!state.cache.summaries[billKey(b)];
}

// ── Search query parsing (substring-only; deep-search bundle deferred) ─────

function parseQuery(raw) {
  if (!raw) return { tokens: [], phrases: [] };
  const phrases = [];
  let s = raw.replace(/"([^"]+)"/g, (_, p) => { phrases.push(p.toLowerCase().trim()); return ' '; });
  const tokens = s.split(/\s+/).filter(Boolean).map(t => t.toLowerCase());
  return { tokens, phrases };
}

function highlightMatches(text, parsedQ) {
  if (!parsedQ || (!parsedQ.tokens.length && !parsedQ.phrases.length)) return escapeHtml(text);
  const all = [...parsedQ.phrases, ...parsedQ.tokens].filter(Boolean).sort((a, b) => b.length - a.length);
  if (!all.length) return escapeHtml(text);
  const re = new RegExp(`(${all.map(t => t.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')).join('|')})`, 'gi');
  return escapeHtml(text).replace(re, '<mark>$1</mark>');
}

// ── Data fetching (sharded) ────────────────────────────────────────────────

async function fetchData(forceRefresh = false) {
  const splash    = document.getElementById('splash');
  const splashErr = document.getElementById('splashError');
  const dataUrl   = _deps.config.dataBaseUrl;

  // 1. IDB cache restore (best-effort, before network)
  if (!forceRefresh) {
    try {
      const [recordsBlob, indexMetaBlob, manifestBlob, metaBlob] = await Promise.all([
        idbGet('blobs', 'bills-records.json'),
        idbGet('blobs', 'bills-index-meta.json'),
        idbGet('blobs', 'bills-manifest.json'),
        idbGet('blobs', 'bills-meta.json'),
      ]);
      if (recordsBlob && Array.isArray(recordsBlob)) {
        state.data.records   = recordsBlob;
        state.data.indexMeta = indexMetaBlob || null;
        state.data.manifest  = manifestBlob  || null;
        state.data.meta      = metaBlob      || null;
      }
    } catch (e) { console.warn('Bills IDB cache miss', e); }
  }

  const haveCache = state.data.records.length > 0;
  const bucket = Math.floor(Date.now() / 300000);
  const v = forceRefresh ? `?v=${Date.now()}` : `?v=${bucket}`;
  const fetchOpts = { cache: 'no-cache' };

  try {
    // 2. Network: fetch index-meta.json (small) first, then all shards in parallel.
    const [indexMeta, manifest, meta] = await Promise.all([
      fetch(dataUrl + CORPUS_PREFIX + 'index-meta.json' + v, fetchOpts).then(r => r.ok ? r.json() : Promise.reject(`index-meta.json: ${r.status}`)),
      fetch(dataUrl + CORPUS_PREFIX + 'manifest.json'   + v, fetchOpts).then(r => r.ok ? r.json() : { texts: {} }).catch(() => ({ texts: {} })),
      fetch(dataUrl + CORPUS_PREFIX + 'meta.json'       + v, fetchOpts).then(r => r.ok ? r.json() : null).catch(() => null),
    ]);

    const shardList = indexMeta?.shards || [];
    if (!shardList.length) {
      throw new Error('index-meta.json has no shards listed');
    }

    const shardJsons = await Promise.all(shardList.map(s =>
      fetch(dataUrl + CORPUS_PREFIX + s.file + v, fetchOpts)
        .then(r => r.ok ? r.json() : Promise.reject(`${s.file}: ${r.status}`))
    ));

    // 3. Merge shards into a flat array, in shard order (newest first across shards).
    const records = [];
    for (const s of shardJsons) {
      if (Array.isArray(s.records)) records.push(...s.records);
    }

    state.data.records   = records;
    state.data.indexMeta = indexMeta;
    state.data.manifest  = manifest;
    state.data.meta      = meta;

    // Cache under bills-prefixed IDB keys so DRSC / CAG / Bills don't collide.
    idbPut('blobs', 'bills-records.json',    records).catch(() => {});
    idbPut('blobs', 'bills-index-meta.json', indexMeta).catch(() => {});
    idbPut('blobs', 'bills-manifest.json',   manifest).catch(() => {});
    if (meta) idbPut('blobs', 'bills-meta.json', meta).catch(() => {});
  } catch (err) {
    console.error('Bills fetch failed', err);
    if (!haveCache) {
      _deps.ui.toast('Could not fetch Bills data — see console for details');
      return false;
    }
    _deps.ui.toast('Bills offline — using cached data');
  }

  splash?.classList.add('hide');
  return true;
}

async function fetchBillText(bill) {
  const key = billKey(bill);
  if (state.cache.text[key]) return state.cache.text[key];

  try {
    const cached = await idbGet('texts', key);
    if (cached) {
      state.cache.text[key] = cached;
      return cached;
    }
  } catch {}

  const entry = state.data.manifest?.texts?.[bill.compositeId];
  if (!entry) return null;
  try {
    const url = entry.url || `text/${bill.compositeId}.txt`;
    const res = await fetch(_deps.config.dataBaseUrl + CORPUS_PREFIX + url);
    if (!res.ok) return null;
    const text = await res.text();
    state.cache.text[key] = text;
    idbPut('texts', key, text).catch(() => {});
    return text;
  } catch (e) {
    console.warn('Bills: failed to fetch text', e);
    return null;
  }
}

// ── Filter / list ───────────────────────────────────────────────────────────

function getAllBills() {
  return state.data.records.map(b => ({
    ...b,
    _date: billDate(b),
    _statusInfo: statusInfo(b),
    _typeInfo: typeInfo(b),
    _houseInfo: houseInfo(b),
  }));
}

function applyFilters() {
  const all = getAllBills();
  const f = state.filters;
  const rawQ = f.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;

  const filtered = all.filter(b => {
    if (f.status && b.status !== f.status) return false;
    if (f.billType && b.billType !== f.billType) return false;
    if (f.billCategory && b.billCategory !== f.billCategory) return false;
    if (f.billYear && String(b.billYear || '') !== f.billYear) return false;
    if (f.billIntroducedInHouse && b.billIntroducedInHouse !== f.billIntroducedInHouse) return false;
    if (!parsedQ) return true;

    const titleLower = (b.billName || '').toLowerCase();
    const ministryLower = (b.ministryName || '').toLowerCase();
    const introducerLower = (b.billIntroducedBy || '').toLowerCase();
    const cached = state.cache.text[billKey(b)];
    const cachedLower = cached ? cached.toLowerCase() : '';

    function tokenHits(t) {
      return titleLower.includes(t) || ministryLower.includes(t) || introducerLower.includes(t) || (cachedLower && cachedLower.includes(t));
    }
    function phraseHits(p) {
      return titleLower.includes(p) || ministryLower.includes(p) || introducerLower.includes(p) || (cachedLower && cachedLower.includes(p));
    }
    return parsedQ.tokens.every(tokenHits) && parsedQ.phrases.every(phraseHits);
  });

  filtered.sort((a, b) => {
    switch (f.sort) {
      case 'year_asc':  return (a.billYear || 0) - (b.billYear || 0);
      case 'date_desc': return (b._date || 0) - (a._date || 0);
      case 'date_asc':  return (a._date || 0) - (b._date || 0);
      case 'year_desc':
      default:          return (b.billYear || 0) - (a.billYear || 0);
    }
  });

  state.filtered = filtered;
  renderList();
  renderResultsLine();
}

function renderResultsLine() {
  const el = document.getElementById('resultsLine');
  if (!el) return;
  const total = state.data.records.length;
  const shown = state.filtered.length;
  const meta = state.data.meta;
  const indexMeta = state.data.indexMeta;
  let metaLine = '';
  if (indexMeta?.scraped_at) {
    metaLine = `Mirror updated <b>${escapeHtml(indexMeta.scraped_at.replace('T', ' ').replace('Z', ' UTC'))}</b>`;
  } else if (meta?.last_update) {
    metaLine = `Mirror updated <b>${escapeHtml(meta.last_update.replace('T', ' ').replace('Z', ' UTC'))}</b>`;
  }
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  const indexLine = withText
    ? `<span>Title search · <b>${withText}</b> bills with text</span>`
    : '';
  el.innerHTML = `Showing <b>${shown}</b> of <b>${total}</b> bills. ${metaLine} ${indexLine}`;
}

function renderList() {
  const list = document.getElementById('reportsList');
  if (!list) return;
  if (!state.filtered.length) {
    list.innerHTML = `<div class="empty-state"><h3>No bills match</h3><p>Try clearing filters.</p></div>`;
    return;
  }
  const slice = state.filtered.slice(0, 200);
  const rawQ = state.filters.search.trim();
  const parsedQ = rawQ ? parseQuery(rawQ) : null;
  list.innerHTML = slice.map(b => {
    const titleHTML = parsedQ ? highlightMatches(b.billName || '(untitled)', parsedQ)
                              : escapeHtml(b.billName || '(untitled)');
    const hi = b._houseInfo;
    const ti = b._typeInfo;
    const si = b._statusInfo;
    const subline = [
      b.billNumber ? `Bill ${b.billNumber}` : null,
      b.ministryName,
      b.billIntroducedBy,
    ].filter(Boolean).join(' · ');
    const yearStr = b.billYear ?? '—';
    return `
      <div class="report-row" data-key="${escapeHtml(billKey(b))}">
        <div>
          <div class="report-title">${titleHTML}</div>
          <div class="report-meta">${escapeHtml(subline) || '—'}</div>
        </div>
        <span class="house-pill house-${hi.pill}" title="${escapeHtml(b.billIntroducedInHouse || '')}">${escapeHtml(hi.short)}</span>
        <span class="cat-badge cat-${ti.class}" title="${escapeHtml(b.billType || '')}">${escapeHtml(ti.short)}</span>
        <span class="cat-badge cat-${si.class}" title="${escapeHtml(b.status || '')}">${escapeHtml(si.label)}</span>
        <span class="report-meta">${escapeHtml(String(yearStr))}</span>
        <span class="text-status ${hasSummary(b) ? 'summary' : (hasExtractedText(b) ? 'ok' : '')}">
          ${hasSummary(b) ? 'summary' : (hasExtractedText(b) ? 'text' : 'metadata')}
        </span>
      </div>
    `;
  }).join('');
  if (state.filtered.length > 200) {
    list.insertAdjacentHTML('beforeend',
      `<div class="empty-state" style="padding:18px"><p>Showing first 200 of ${state.filtered.length} matches — refine filters to narrow further.</p></div>`);
  }
}

function renderHeaderStats() {
  const el = document.getElementById('headerStats');
  if (!el) return;
  const total = state.data.records.length;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  const becameLaw = state.data.records.filter(b => b.actNo).length;
  el.innerHTML = `
    <span><b>${total}</b> bills</span>
    <span><b>${withText}</b> with text</span>
    <span><b>${becameLaw}</b> became law</span>
  `;
}

function populateFilters() {
  const records = state.data.records;
  const statusSet = new Set();
  const typeSet = new Set();
  const catSet = new Set();
  const yearSet = new Set();
  const houseSet = new Set();
  for (const b of records) {
    if (b.status) statusSet.add(b.status);
    if (b.billType) typeSet.add(b.billType);
    if (b.billCategory) catSet.add(b.billCategory);
    if (b.billYear) yearSet.add(b.billYear);
    if (b.billIntroducedInHouse) houseSet.add(b.billIntroducedInHouse);
  }

  function fill(id, values, label, sortFn) {
    const sel = document.getElementById(id);
    if (!sel) return;
    const sorted = [...values].sort(sortFn || ((a, b) => String(a).localeCompare(String(b))));
    sel.innerHTML = `<option value="">${label}</option>` +
      sorted.map(v => `<option value="${escapeHtml(String(v))}">${escapeHtml(String(v))}</option>`).join('');
  }
  fill('filterStatus',   statusSet, 'All statuses');
  fill('filterBillType', typeSet,   'All bill types');
  fill('filterBillCategory', catSet, 'All categories');
  fill('filterHouse',    houseSet,  'Both houses');
  fill('filterYear',     yearSet,   'All years', (a, b) => b - a);

  // Restore selections
  const restore = (id, key) => { const el = document.getElementById(id); if (el) el.value = state.filters[key] || ''; };
  restore('filterStatus', 'status');
  restore('filterBillType', 'billType');
  restore('filterBillCategory', 'billCategory');
  restore('filterHouse', 'billIntroducedInHouse');
  restore('filterYear', 'billYear');
}

// ── Detail modal ────────────────────────────────────────────────────────────

function openBillByKey(key) {
  const all = getAllBills();
  const b = all.find(x => billKey(x) === key);
  if (!b) return;
  if (_deps.ai.streaming() && state.streamingContext?.billKey !== key) {
    _deps.ai.stop();
    state.streamingContext = null;
  }
  state.selectedBill = b;
  state.dialogChat = state.cache.chats[key] ? [...state.cache.chats[key]] : [];
  document.getElementById('reportTitle').textContent = b.billName || '(untitled)';
  renderDetailsTab(b);
  switchReportTab('details');
  document.getElementById('reportModal').classList.add('open');
}

function _fileLink(label, url) {
  if (!url) return '';
  const filename = String(url).split('/').pop();
  return `<dt>${escapeHtml(label)}</dt><dd><a href="${escapeHtml(url)}" target="_blank" rel="noopener">${escapeHtml(filename)}</a></dd>`;
}

function renderDetailsTab(b) {
  const ti = typeInfo(b);
  const si = statusInfo(b);
  document.getElementById('detailsTab').innerHTML = `
    <dl class="meta-grid">
      <dt>Title</dt><dd>${escapeHtml(b.billName || '—')}</dd>
      ${b.billNumber ? `<dt>Bill no.</dt><dd>${escapeHtml(b.billNumber)} of ${b.billYear ?? '—'}</dd>` : ''}
      ${b.billType ? `<dt>Type</dt><dd><span class="cat-badge cat-${ti.class}">${escapeHtml(b.billType)}</span></dd>` : ''}
      ${b.billCategory ? `<dt>Category</dt><dd>${escapeHtml(b.billCategory)}</dd>` : ''}
      ${b.billIntroducedInHouse ? `<dt>Introduced in</dt><dd>${escapeHtml(b.billIntroducedInHouse)}</dd>` : ''}
      ${b.billIntroducedBy ? `<dt>Introduced by</dt><dd>${escapeHtml(b.billIntroducedBy)}</dd>` : ''}
      ${b.billIntroducedDate ? `<dt>Introduced on</dt><dd>${escapeHtml(b.billIntroducedDate.split(' ')[0])}</dd>` : ''}
      ${b.ministryName ? `<dt>Ministry</dt><dd>${escapeHtml(b.ministryName)}</dd>` : ''}
      <dt>Status</dt><dd><span class="cat-badge cat-${si.class}">${escapeHtml(b.status || '—')}</span></dd>
      ${b.billPassedInLSDate ? `<dt>Passed in LS</dt><dd>${escapeHtml(b.billPassedInLSDate.split(' ')[0])}</dd>` : ''}
      ${b.billPassedInRSDate ? `<dt>Passed in RS</dt><dd>${escapeHtml(b.billPassedInRSDate.split(' ')[0])}</dd>` : ''}
      ${b.referredToCommitteeDate ? `<dt>Referred to cmte</dt><dd>${escapeHtml(b.referredToCommitteeDate.split(' ')[0])}</dd>` : ''}
      ${b.reportPresentedDate ? `<dt>Cmte report presented</dt><dd>${escapeHtml(b.reportPresentedDate.split(' ')[0])}</dd>` : ''}
      ${b.actNo ? `<dt>Act no.</dt><dd>${escapeHtml(b.actNo)} of ${b.actYear ?? '—'}</dd>` : ''}
      ${b.billAssentedDate ? `<dt>Assented on</dt><dd>${escapeHtml(b.billAssentedDate.split(' ')[0])}</dd>` : ''}
    </dl>

    <h4 style="margin-top:18px; margin-bottom:8px">Available PDFs</h4>
    <dl class="meta-grid">
      ${_fileLink('Introduced version', b.billIntroducedFile)}
      ${_fileLink('Passed in LS', b.billPassedInLSFile)}
      ${_fileLink('Passed in RS', b.billPassedInRSFile)}
      ${_fileLink('Passed (both houses)', b.billPassedInBothHousesFile)}
      ${_fileLink('Errata', b.errataFile)}
      ${_fileLink('Synopsis', b.billSynopsisFile)}
      ${_fileLink('Standing-cmte report', b.reportFile)}
      ${_fileLink('Gazette notification', b.billGazettedFile)}
    </dl>

    <p style="margin-top:14px; font-size:0.82rem; color:var(--muted)">
      ${hasExtractedText(b)
        ? 'Full text has been extracted by the mirror — see the "Full text" tab or generate an AI summary.'
        : 'Full text has not yet been extracted by the mirror. The daily Action picks bills up incrementally — check back, or open a PDF directly.'}
    </p>
  `;
}

async function loadTextTab() {
  const b = state.selectedBill;
  const tab = document.getElementById('textTab');
  if (!b) { tab.innerHTML = ''; return; }
  if (!hasExtractedText(b)) {
    tab.innerHTML = `<p>Full text hasn't been extracted yet. Open a PDF link from the Details tab.</p>`;
    return;
  }
  tab.innerHTML = `<p style="color:var(--muted)">Loading…</p>`;
  const text = await fetchBillText(b);
  if (!text) { tab.innerHTML = `<p>Could not load the extracted text.</p>`; return; }
  tab.innerHTML = `<pre>${escapeHtml(text)}</pre>`;
  renderList();
}

function switchReportTab(name) {
  document.querySelectorAll('#reportModal .tab-btn').forEach(b => b.classList.toggle('active', b.dataset.tab === name));
  document.querySelectorAll('#reportModal .tab-pane').forEach(p => p.classList.remove('active'));
  document.getElementById(name + 'Tab').classList.add('active');
  if (name === 'text')    loadTextTab();
  if (name === 'summary') renderSummaryTab();
  if (name === 'chat')    renderChatTab();
}

function renderSummaryTab() {
  const tab = document.getElementById('summaryTab');
  const b = state.selectedBill;
  if (!b) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = billKey(b);
  const cached = state.cache.summaries[key];
  const isStreaming = state.streamingContext?.billKey === key
                  &&  state.streamingContext?.tab === 'summary';

  if (isStreaming) {
    tab.innerHTML = `
      <div class="summary-actions">
        <span class="label">Generating summary… (streams in below)</span>
        <button class="ghost sm" id="stopSummaryBtn">Stop</button>
      </div>
      <div class="summary-box" id="summaryBox">${escapeHtml(cached || '')}</div>
    `;
    document.getElementById('stopSummaryBtn').addEventListener('click', () => {
      _deps.ai.stop();
      state.streamingContext = null;
    });
    return;
  }

  tab.innerHTML = `
    <div class="summary-actions">
      <span class="label">Generate a plain-English summary using your configured AI:</span>
      <button class="primary" id="generateSummaryBtn">${cached ? 'Regenerate' : 'Generate'}</button>
      <button class="ghost sm" id="copySummaryBtn" ${cached ? '' : 'style="display:none"'}>Copy</button>
    </div>
    <div class="summary-box" id="summaryBox">${cached ? escapeHtml(cached) : 'No summary yet.'}</div>
  `;
  document.getElementById('generateSummaryBtn').addEventListener('click', generateSummary);
  document.getElementById('copySummaryBtn').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('summaryBox').textContent || '');
    _deps.ui.toast('Copied');
  });
}

function renderChatTab() {
  const tab = document.getElementById('chatTab');
  const b = state.selectedBill;
  if (!b) { tab.innerHTML = ''; return; }
  if (!_deps.ai.isUsable()) {
    tab.innerHTML = _deps.ai.notReadyHTML();
    _deps.ai.bindNotReadyCTA(tab);
    return;
  }
  const key = billKey(b);
  const isStreaming = state.streamingContext?.billKey === key
                  &&  state.streamingContext?.tab === 'chat';

  const messages = state.dialogChat.length
    ? state.dialogChat
    : [{ role: 'system', content: 'Ask anything about this bill. Your question + the bill text are sent to the AI you configured (local Gemma or BYOK).' }];

  const threadHTML = messages.map(m => {
    const cls = `chat-msg ${m.role}${m.error ? ' error' : ''}`;
    return `<div class="${cls}">${escapeHtml(m.content)}</div>`;
  }).join('');

  const searchOn = _deps.search.isConfigured();
  tab.innerHTML = `
    <div class="chat-thread" id="chatThread">${threadHTML}</div>
    <div class="chat-input-row">
      <textarea id="chatInput" rows="2" placeholder="Ask a question about this bill..." ${isStreaming ? 'disabled' : ''}></textarea>
      ${searchOn ? `<button class="ghost sm" id="chatSearchSendBtn" title="Search the web AND Send" ${isStreaming ? 'disabled' : ''}>&#127760;</button>` : ''}
      <button class="primary" id="chatSendBtn" ${isStreaming ? 'disabled' : ''}>Send</button>
      <button class="ghost sm" id="chatStopBtn" ${isStreaming ? '' : 'style="display:none"'}>Stop</button>
    </div>
  `;
  document.getElementById('chatSendBtn').addEventListener('click', () => chatSend({}));
  if (searchOn) document.getElementById('chatSearchSendBtn').addEventListener('click', () => chatSend({ withSearch: true }));
  document.getElementById('chatStopBtn').addEventListener('click', () => {
    _deps.ai.stop();
    state.streamingContext = null;
  });
  document.getElementById('chatInput').addEventListener('keydown', e => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); chatSend({}); }
  });
  const t = document.getElementById('chatThread');
  if (t) t.scrollTop = t.scrollHeight;
}

function _truncateForContext(text) {
  const limit = _deps.ai.mode() === 'local' ? 12000 : 60000;
  if (text.length <= limit) return text;
  return text.slice(0, limit) + '\n\n[...truncated for context window...]';
}

async function generateSummary() {
  const b = state.selectedBill;
  if (!b) return;
  const text = await fetchBillText(b);
  if (!text) {
    _deps.ui.toast('Full text not available — extract pending');
    return;
  }
  const key = billKey(b);
  const prompt = SUMMARY_PROMPT.replace('{TEXT}', _truncateForContext(text));
  const messages = [
    { role: 'system', content: 'You are a careful, accurate summariser of Indian parliamentary bills.' },
    { role: 'user',   content: prompt },
  ];
  state.cache.summaries[key] = '';
  state.streamingContext = { billKey: key, tab: 'summary' };
  renderSummaryTab();
  try {
    await _deps.ai.generate(messages, (tok) => {
      state.cache.summaries[key] = (state.cache.summaries[key] || '') + tok;
      const box = document.getElementById('summaryBox');
      if (box && state.streamingContext?.billKey === key) {
        box.textContent = state.cache.summaries[key];
      }
    });
    idbPut('summaries', key, state.cache.summaries[key]).catch(() => {});
  } catch (e) {
    state.cache.summaries[key] = (state.cache.summaries[key] || '') + '\n\n[Error: ' + e.message + ']';
  } finally {
    state.streamingContext = null;
    renderSummaryTab();
    renderList();
  }
}

async function chatSend(opts) {
  opts = opts || {};
  const b = state.selectedBill;
  if (!b) return;
  const input = document.getElementById('chatInput');
  const q = input.value.trim();
  if (!q) return;
  if (_deps.ai.streaming()) { _deps.ui.toast('Already responding…'); return; }
  const text = await fetchBillText(b);
  if (!text) { _deps.ui.toast('Full text not available'); return; }
  state.dialogChat.push({ role: 'user', content: q });
  let searchResults = null;
  if (opts.withSearch) {
    if (!_deps.search.isConfigured()) {
      state.dialogChat.push({ role: 'system', content: 'Web search not configured. Open Settings → Web search to add a provider.' });
      input.value = '';
      renderChatTab();
      return;
    }
    state.dialogChat.push({ role: 'system', content: `Searching the web for "${q}"…` });
    renderChatTab();
    try {
      searchResults = await _deps.search.run(q);
      const resultLine = searchResults.length
        ? `Found ${searchResults.length} result${searchResults.length === 1 ? '' : 's'}: ${searchResults.map(x => x.title).slice(0, 3).join(' · ')}${searchResults.length > 3 ? '…' : ''}`
        : 'No web results.';
      state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: resultLine };
    } catch (e) {
      state.dialogChat[state.dialogChat.length - 1] = { role: 'system', content: 'Search failed: ' + e.message };
      searchResults = null;
    }
  }
  state.dialogChat.push({ role: 'assistant', content: '' });
  state.streamingContext = { billKey: billKey(b), tab: 'chat' };
  input.value = '';
  renderChatTab();
  const summary = state.cache.summaries[billKey(b)];
  const userPrompt = buildAskPrompt({
    summary: summary || null,
    text: _truncateForContext(text),
    searchResults,
    question: q,
  });
  const messages = [
    { role: 'system', content: 'You answer questions about bills from the Indian Parliament. Use only the supplied material. If the answer is not present, say so.' },
    { role: 'user',   content: userPrompt },
  ];
  try {
    await _deps.ai.generate(messages, (tok) => {
      const last = state.dialogChat[state.dialogChat.length - 1];
      last.content += tok;
      const lastEl = document.querySelector('#chatThread .chat-msg.assistant:last-child');
      if (lastEl) {
        lastEl.textContent = last.content;
        const t = document.getElementById('chatThread');
        if (t) t.scrollTop = t.scrollHeight;
      }
    });
  } catch (e) {
    const last = state.dialogChat[state.dialogChat.length - 1];
    last.error = true;
    last.content = 'Error: ' + e.message;
  } finally {
    state.streamingContext = null;
    renderChatTab();
    const k = billKey(b);
    state.cache.chats[k] = [...state.dialogChat];
    idbPut('chats', k, state.dialogChat).catch(() => {});
  }
}

async function loadCachedTexts() {
  // Cursor through 'texts' IDB store, pick rows whose key starts with 'bills|'.
  // Safe to no-op on cursor errors — nothing depends on this for correctness.
  let n = 0;
  try {
    const db = await import('../../deps.js').then(m => m.openIDB());
    const tx = db.transaction('texts', 'readonly');
    const store = tx.objectStore('texts');
    await new Promise((resolve) => {
      const req = store.openCursor();
      req.onsuccess = () => {
        const c = req.result;
        if (!c) return resolve();
        const k = c.key;
        if (typeof k === 'string' && k.startsWith('bills|')) {
          state.cache.text[k] = c.value;
          n++;
        }
        c.continue();
      };
      req.onerror = () => resolve();
    });
  } catch {}
  return n;
}

async function loadCachedSummaries() {
  try {
    const db = await import('../../deps.js').then(m => m.openIDB());
    const tx = db.transaction('summaries', 'readonly');
    const store = tx.objectStore('summaries');
    await new Promise((resolve) => {
      const req = store.openCursor();
      req.onsuccess = () => {
        const c = req.result;
        if (!c) return resolve();
        if (typeof c.key === 'string' && c.key.startsWith('bills|')) {
          state.cache.summaries[c.key] = c.value;
        }
        c.continue();
      };
      req.onerror = () => resolve();
    });
  } catch {}
}

async function loadCachedChats() {
  try {
    const db = await import('../../deps.js').then(m => m.openIDB());
    const tx = db.transaction('chats', 'readonly');
    const store = tx.objectStore('chats');
    await new Promise((resolve) => {
      const req = store.openCursor();
      req.onsuccess = () => {
        const c = req.result;
        if (!c) return resolve();
        if (typeof c.key === 'string' && c.key.startsWith('bills|')) {
          state.cache.chats[c.key] = c.value;
        }
        c.continue();
      };
      req.onerror = () => resolve();
    });
  } catch {}
}

// ── Filter row + handlers ──────────────────────────────────────────────────

function renderFilterRow() {
  const container = document.getElementById('filtersContainer');
  if (!container) return;
  container.innerHTML = `
    <input type="search" id="filterSearch" placeholder="Search bills..." autocomplete="off">
    <select id="filterStatus"><option value="">All statuses</option></select>
    <select id="filterBillType"><option value="">All bill types</option></select>
    <select id="filterBillCategory"><option value="">All categories</option></select>
    <select id="filterHouse"><option value="">Both houses</option></select>
    <select id="filterYear"><option value="">All years</option></select>
    <select id="filterSort">
      <option value="year_desc">Newest year first</option>
      <option value="year_asc">Oldest year first</option>
      <option value="date_desc">Newest by date</option>
      <option value="date_asc">Oldest by date</option>
    </select>
    <button class="ghost sm" id="resetFiltersBtn" title="Reset filters">&times;</button>
  `;
  document.getElementById('filterSearch').value = state.filters.search || '';
  document.getElementById('filterSort').value   = state.filters.sort   || 'year_desc';
}

function attachHandlers() {
  const onSearch = debounce(() => {
    state.filters.search = document.getElementById('filterSearch').value;
    applyFilters();
  }, 200);
  document.getElementById('filterSearch')?.addEventListener('input', onSearch);

  function bindSelect(id, key) {
    document.getElementById(id)?.addEventListener('change', e => {
      state.filters[key] = e.target.value;
      applyFilters();
    });
  }
  bindSelect('filterStatus', 'status');
  bindSelect('filterBillType', 'billType');
  bindSelect('filterBillCategory', 'billCategory');
  bindSelect('filterHouse', 'billIntroducedInHouse');
  bindSelect('filterYear', 'billYear');
  bindSelect('filterSort', 'sort');

  document.getElementById('resetFiltersBtn')?.addEventListener('click', () => {
    state.filters = { search: '', status: '', billType: '', billCategory: '', billYear: '', billIntroducedInHouse: '', sort: 'year_desc' };
    renderFilterRow();
    populateFilters();
    applyFilters();
  });

  // Row click → open detail. Delegate at #reportsList because rows are
  // re-rendered into innerHTML on every applyFilters().
  document.getElementById('reportsList')?.addEventListener('click', e => {
    const row = e.target.closest('.report-row');
    if (!row) return;
    const key = row.dataset.key;
    if (key && key.startsWith('bills|')) openBillByKey(key);
  });
}

// ── Activation ──────────────────────────────────────────────────────────────

async function activate(deps) {
  _deps = deps;

  renderFilterRow();
  attachHandlers();

  if (!_activated) {
    _activated = true;
    const ok = await fetchData();
    if (!ok) return false;

    populateFilters();
    renderHeaderStats();
    applyFilters();

    loadCachedSummaries();
    loadCachedChats();
    loadCachedTexts().then((n) => {
      if (n) {
        renderList();
        renderResultsLine();
      }
    });
  } else {
    populateFilters();
    renderHeaderStats();
    applyFilters();
  }

  return true;
}

function refreshAIDependentTabs() {
  if (!state.selectedBill) return;
  const sumActive  = document.getElementById('summaryTab')?.classList.contains('active');
  const chatActive = document.getElementById('chatTab')?.classList.contains('active');
  if (sumActive)  renderSummaryTab();
  if (chatActive) renderChatTab();
}

// ── Settings section ───────────────────────────────────────────────────────

function renderSettingsSection(container) {
  const indexMeta = state.data.indexMeta;
  const meta = state.data.meta;
  const totalBills = state.data.records.length;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;

  container.innerHTML = `
    <div class="settings-section">
      <h3>Bills (Indian Parliament)</h3>
      <p>Bills are indexed via sansad.in's public legislation API and mirrored daily. Full corpus: ${totalBills} bills (${(state.data.indexMeta?.shards?.length || 0)} shards). Text extraction backfill is incremental — currently ${withText} bills have extracted text.</p>
      <p style="margin-top:8px; font-size:0.82rem; color:var(--muted)">
        ${meta?.last_update ? 'Mirror last updated ' + escapeHtml(meta.last_update) + '. ' : ''}
        ${meta?.in_rate_limit_cooldown ? 'Currently in rate-limit cooldown — extractions resume next cron tick. ' : ''}
        Search is currently title + ministry + introducer + cached-text only. Deep search (full corpus body index) is on the v0.6 roadmap.
      </p>
    </div>
  `;
}

function applySettingsFromUI() {
  // No settings yet that need persisting beyond the corpus's own state.
}

// ── fetchStatus (chip status display) ──────────────────────────────────────

async function fetchStatus() {
  const meta = state.data.meta;
  const total = state.data.records.length;
  const withText = Object.keys(state.data.manifest?.texts || {}).length;
  if (!meta) return { lastUpdate: null, items: total, withText, error: null };
  return {
    lastUpdate: meta.last_update || null,
    items: meta.total || total,
    withText,
    error: meta.last_run_status === 'rate_limited' ? 'rate-limited' : null,
  };
}

// ── JS API surface ─────────────────────────────────────────────────────────

const api = {
  list({ status, billType, billCategory, billYear, billIntroducedInHouse } = {}) {
    return getAllBills().filter(b => {
      if (status && b.status !== status) return false;
      if (billType && b.billType !== billType) return false;
      if (billCategory && b.billCategory !== billCategory) return false;
      if (billYear != null && String(b.billYear) !== String(billYear)) return false;
      if (billIntroducedInHouse && b.billIntroducedInHouse !== billIntroducedInHouse) return false;
      return true;
    });
  },
  get(key) {
    return getAllBills().find(b => billKey(b) === key) || null;
  },
  search(query) {
    const parsedQ = parseQuery(query);
    if (!parsedQ.tokens.length && !parsedQ.phrases.length) return getAllBills();
    return getAllBills().filter(b => {
      const titleLower = (b.billName || '').toLowerCase();
      const ministryLower = (b.ministryName || '').toLowerCase();
      const introducerLower = (b.billIntroducedBy || '').toLowerCase();
      const cached = state.cache.text[billKey(b)];
      const cachedLower = cached ? cached.toLowerCase() : '';
      const tokHit = t => titleLower.includes(t) || ministryLower.includes(t) || introducerLower.includes(t) || (cachedLower && cachedLower.includes(t));
      const phHit  = p => titleLower.includes(p) || ministryLower.includes(p) || introducerLower.includes(p) || (cachedLower && cachedLower.includes(p));
      return parsedQ.tokens.every(tokHit) && parsedQ.phrases.every(phHit);
    });
  },
  open(key) {
    const b = api.get(key);
    if (!b) return false;
    openBillByKey(billKey(b));
    return true;
  },
};

// ── Export the corpus contract ─────────────────────────────────────────────

export const BillsCorpus = {
  id:          'bills',
  label:       'Bills',
  shortLabel:  'Bills',
  macroGroup:  'legislation',
  primaryUnit: 'bill',

  fetchStatus,
  activate,

  api,
  renderSettingsSection,
  applySettingsFromUI,
  refreshAIDependentTabs,
};
